# Module: Pandas Assignments
## Lesson: Pandas
### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.

In [ ]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in d:\udemy\datascience\python\venv\lib\site-packages (from pandas) (2.4.0)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\udemy\datascience\python\venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in d:\udemy\datascience\python\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp314-cp314-win_amd64.whl (11.1 MB)
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.1 MB 1.5 MB/s eta 0:00:08
   -- ------------------------------------- 0.8/11.1 MB 1.5 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/11.1 MB 1.6 MB/s eta 0:00:07
   ---- ----------------------------------- 1.3/11.1 MB 1.3 MB/s eta 0:00:08
   ---- ----------------------------------- 1.3/11.1 MB 1.3 MB/s eta 0:00:08
   ----- ---------------------------------- 1.6/11.1 MB 1.2 MB/s eta 0:00:08
   ------- -------------------------------- 2.1/11.1 MB 1.3 MB/s eta 0:00:08
   --------- ------------------------------ 2.6/11.1 MB 1.4 MB/s eta 0:00:06
   ---------- ----------------------------- 2.9/11.1 MB 1.4 MB/s eta 0:00:06
   ----------- ---------------------------- 3.1/11.1 MB 1.5 MB/s eta 0:00:06
   ------------ --------------------------- 3.4/11.1 MB 1.4 MB/s eta 0:00:06
   --------------- ------------------------ 4.2/11.1 MB 1.7 MB/s eta 0:00:05
   ---------------- ----------------------- 4.5/11.1 MB 1.6 MB/s eta 0:00:05
   ---------------- ----------------------- 4.5/11.1 MB 1.6 MB/s eta 0:00:05
   ----------------- ---------------------- 5.0/11.1 MB 1.6 MB/s eta 0:00:04
   ------------------- -------------------- 5.5/11.1 MB 1.6 MB/s eta 0:00:04
   --------------------- ------------------ 6.0/11.1 MB 1.7 MB/s eta 0:00:04
   ----------------------- ---------------- 6.6/11.1 MB 1.7 MB/s eta 0:00:03
   ----------------------- ---------------- 6.6/11.1 MB 1.7 MB/s eta 0:00:03
   ------------------------ --------------- 6.8/11.1 MB 1.6 MB/s eta 0:00:03
   ------------------------- -------------- 7.1/11.1 MB 1.6 MB/s eta 0:00:03
   --------------------------- ------------ 7.6/11.1 MB 1.6 MB/s eta 0:00:03
   ----------------------------- ---------- 8.1/11.1 MB 1.7 MB/s eta 0:00:02
   ------------------------------ --------- 8.4/11.1 MB 1.7 MB/s eta 0:00:02
   ------------------------------- -------- 8.7/11.1 MB 1.6 MB/s eta 0:00:02
   ------------------------------- -------- 8.7/11.1 MB 1.6 MB/s eta 0:00:02
   ------------------------------- -------- 8.7/11.1 MB 1.6 MB/s eta 0:00:02
   ------------------------------- -------- 8.7/11.1 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 8.9/11.1 MB 1.5 MB/s eta 0:00:02
   --------------------------------- ------ 9.2/11.1 MB 1.5 MB/s eta 0:00:02
   ----------------------------------- ---- 10.0/11.1 MB 1.5 MB/s eta 0:00:01
   ------------------------------------- -- 10.5/11.1 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 1.6 MB/s  0:00:06
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: pytz, tzdata, pandas

   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [tzdata]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed pandas-2.3.3 pytz-2025.2 tzdata-2025.3

In [1]:
import pandas as pd
import numpy as np

In [7]:
df=pd.DataFrame(np.random.randint(1,100,size=(6,4)),columns=['A','B','C','D'])
df

    A   B   C   D
0  85  10  65  35
1  14  49  38  61
2  39  61  74  69
3  76  53  56   6
4  24  47  65  30
5  21  20  60  92

2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

In [10]:
df=pd.DataFrame(np.random.randint(1,100,size=(3,3)),columns=['A','B','C'],index=['X','Y','Z'])
df

    A   B   C
X  64  11  79
Y  94  56   7
Z  57  71  84

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.

In [14]:
df=pd.DataFrame(np.random.randint(1,10,size=(5,3)),columns=['A','B','C'])
df['Product']=df['A']*df['B']
df

   A  B  C  Product
0  3  2  9        6
1  4  7  7       28
2  9  2  6       18
3  4  1  2        4
4  8  7  1       56

2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [23]:
df=pd.DataFrame(np.random.randint(1,10,size=(4,3)),columns=['A','B','C'])
df['RowSum']=df.sum(axis=1)
df.loc['ColSum']=df.sum(axis=0)

df

         A   B   C  RowSum
0        1   8   4      13
1        9   9   5      23
2        4   2   7      13
3        5   7   1      13
ColSum  19  26  17      62

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

In [ ]:
df=pd.DataFrame(np.random.randint(1,10,size=(5,3)))
df[1][1]=np.nan
df[2][1]=np.nan
df[1][3]=np.nan

df.fillna(df.mean(),inplace=True)
df

C:\Users\sambhav_surthi\AppData\Local\Temp\ipykernel_14504\2082558526.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[2][1]=np.nan

   0         1     2
0  5  2.000000  2.00
1  8  2.333333  3.25
2  9  3.000000  3.00
3  7  2.333333  6.00
4  5  2.000000  2.00

2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [46]:
df=pd.DataFrame(np.random.randint(1,10,size=(5,3)))
df.iloc[0,1]=np.nan
df.iloc[1,2]=np.nan
df.iloc[3,1]=np.nan

df.dropna(inplace=True)

df

   0    1    2
2  5  4.0  5.0
4  5  3.0  9.0

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.

In [7]:
df=pd.DataFrame({'Categories':np.random.choice(['A','B','C'],size=10),'Values':np.random.randint(1,100,size=10)})
print(df)

grouped=df.groupby('Categories')['Values'].agg(['sum','mean'])
grouped

  Categories  Values
0          B      99
1          A      55
2          A      47
3          C       4
4          B      94
5          C      46
6          C      77
7          A      81
8          B      92
9          A      30

            sum       mean
Categories
A           213  53.250000
B           285  95.000000
C           127  42.333333

2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

In [9]:
df=pd.DataFrame({'Product':np.random.randint(1,100,size=10),'Category':np.random.choice(['A','B','C'],size=10),'Sales':np.random.randint(1,100,size=10)})
print(df)

grouped=df.groupby('Category')['Sales'].sum()
grouped

   Product Category  Sales
0       35        A     43
1       15        A     71
2       74        B      4
3       77        B     69
4       89        B     49
5       82        C     44
6       68        B     81
7       63        B     52
8       18        C     30
9       41        B     74

Category
A    114
B    329
C     74
Name: Sales, dtype: int64

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.

In [14]:
df1=pd.DataFrame({'Product':np.random.randint(1,100,size=10),'Categories':np.random.choice(['A','B','C'],size=10),'Sales':np.random.randint(1,100,size=10)})
print(df1)

df2=pd.DataFrame({'Categories':np.random.choice(['A','B','C'],size=10),'Values':np.random.randint(1,100,size=10)})
print(df2)

main=pd.merge(df1,df2,on='Categories')
main

   Product Categories  Sales
0       70          C     79
1       59          A     33
2        3          C     95
3       28          B     35
4        7          B     18
5       34          B      8
6       12          B     37
7       80          C     79
8       22          B      7
9        9          C     51
  Categories  Values
0          B      86
1          B      84
2          A      13
3          A      23
4          B      66
5          A       1
6          B      86
7          A      26
8          C      19
9          A      57

    Product Categories  Sales  Values
0        70          C     79      19
1        59          A     33      13
2        59          A     33      23
3        59          A     33       1
4        59          A     33      26
5        59          A     33      57
6         3          C     95      19
7        28          B     35      86
8        28          B     35      84
9        28          B     35      66
10       28          B     35      86
11        7          B     18      86
12        7          B     18      84
13        7          B     18      66
14        7          B     18      86
15       34          B      8      86
16       34          B      8      84
17       34          B      8      66
18       34          B      8      86
19       12          B     37      86
20       12          B     37      84
21       12          B     37      66
22       12          B     37      86
23       80          C     79      19
24       22          B      7      86
25       22          B      7      84
26       22          B      7      66
27       22          B      7      86
28        9          C     51      19

2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

In [22]:
df1=pd.DataFrame({'Product':np.random.randint(1,100,size=10),'some':np.random.choice(['A','B','C'],size=10),'Sales':np.random.randint(1,100,size=10)})
print(df1)

df2=pd.DataFrame({'Categories':np.random.choice(['A','B','C'],size=10),'Values':np.random.randint(1,100,size=10)})
print(df2)

con=pd.concat([df1,df2],axis=1)
con1=pd.concat([df1,df2],axis=0)
print(con)
print(con1)

   Product some  Sales
0       83    B     96
1       55    A     80
2       68    C     95
3       84    C     57
4       95    B     94
5       47    C     83
6        7    B      8
7       34    A     85
8       16    A     94
9       48    A     14
  Categories  Values
0          B      44
1          B      57
2          A      54
3          C       1
4          B      24
5          A      27
6          C      13
7          A      58
8          A      70
9          C      58
   Product some  Sales Categories  Values
0       83    B     96          B      44
1       55    A     80          B      57
2       68    C     95          A      54
3       84    C     57          C       1
4       95    B     94          B      24
5       47    C     83          A      27
6        7    B      8          C      13
7       34    A     85          A      58
8       16    A     94          A      70
9       48    A     14          C      58
   Product some  Sales Categories  Values
0     83.0    B   96.0        NaN     NaN
1     55.0    A   80.0        NaN     NaN
2     68.0    C   95.0        NaN     NaN
3     84.0    C   57.0        NaN     NaN
4     95.0    B   94.0        NaN     NaN
5     47.0    C   83.0        NaN     NaN
6      7.0    B    8.0        NaN     NaN
7     34.0    A   85.0        NaN     NaN
8     16.0    A   94.0        NaN     NaN
9     48.0    A   14.0        NaN     NaN
0      NaN  NaN    NaN          B    44.0
1      NaN  NaN    NaN          B    57.0
2      NaN  NaN    NaN          A    54.0
3      NaN  NaN    NaN          C     1.0
4      NaN  NaN    NaN          B    24.0
5      NaN  NaN    NaN          A    27.0
6      NaN  NaN    NaN          C    13.0
7      NaN  NaN    NaN          A    58.0
8      NaN  NaN    NaN          A    70.0
9      NaN  NaN    NaN          C    58.0

### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.

2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.

In [23]:
# Create a Pandas DataFrame with a MultiIndex (hierarchical index)
arrays = [['A', 'A', 'B', 'B'], ['one', 'two', 'one', 'two']]
index = pd.MultiIndex.from_arrays(arrays, names=('Category', 'SubCategory'))
df = pd.DataFrame(np.random.randint(1, 100, size=(4, 3)), index=index, columns=['Value1', 'Value2', 'Value3'])
print("MultiIndex DataFrame:")
print(df)

# Basic indexing and slicing operations
print("Indexing at Category 'A':")
print(df.loc['A'])

print("Slicing at Category 'B' and SubCategory 'two':")
print(df.loc[('B', 'two')])

MultiIndex DataFrame:
                      Value1  Value2  Value3
Category SubCategory
A        one              85      35       9
         two              72      83      18
B        one              84      19      60
         two              71      59      80
Indexing at Category 'A':
             Value1  Value2  Value3
SubCategory
one              85      35       9
two              72      83      18
Slicing at Category 'B' and SubCategory 'two':
Value1    71
Value2    59
Value3    80
Name: (B, two), dtype: int64

2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

In [24]:
# Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'
arrays = [['A', 'A', 'B', 'B', 'C', 'C'], ['one', 'two', 'one', 'two', 'one', 'two']]
index = pd.MultiIndex.from_arrays(arrays, names=('Category', 'SubCategory'))
df = pd.DataFrame(np.random.randint(1, 100, size=(6, 3)), index=index, columns=['Value1', 'Value2', 'Value3'])
print("MultiIndex DataFrame:")
print(df)

# Compute the sum of values for each 'Category' and 'SubCategory'
sum_values = df.groupby(['Category', 'SubCategory']).sum()
print("Sum of values:")
print(sum_values)

MultiIndex DataFrame:
                      Value1  Value2  Value3
Category SubCategory
A        one              80      59      92
         two              77      47      53
B        one              93      49       8
         two              59       5      55
C        one               9       6       1
         two               4      97      52
Sum of values:
                      Value1  Value2  Value3
Category SubCategory
A        one              80      59      92
         two              77      47      53
B        one              93      49       8
         two              59       5      55
C        one               9       6       1
         two               4      97      52

### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.

In [26]:
# Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'
date_rng = pd.date_range(start='2022-01-01', end='2022-01-10', freq='D')
df = pd.DataFrame({'Date': np.random.choice(date_rng, size=20), 'Category': np.random.choice(['A', 'B', 'C'], size=20), 'Value': np.random.randint(1, 100, size=20)})
print("Original DataFrame:")
print(df)

# Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'
pivot_table = df.pivot_table(values='Value', index='Date', columns='Category', aggfunc='sum')
print("Pivot Table:")
pivot_table

Original DataFrame:
         Date Category  Value
0  2022-01-04        B     88
1  2022-01-05        A     26
2  2022-01-04        C      8
3  2022-01-01        B     67
4  2022-01-09        A     35
5  2022-01-04        A     25
6  2022-01-01        A     12
7  2022-01-07        C     15
8  2022-01-09        A     93
9  2022-01-09        B     10
10 2022-01-10        A     53
11 2022-01-05        B     37
12 2022-01-04        A     81
13 2022-01-07        B      1
14 2022-01-04        A     88
15 2022-01-08        C      6
16 2022-01-08        C     92
17 2022-01-02        C      6
18 2022-01-02        C     14
19 2022-01-04        B     86
Pivot Table:

Category        A      B     C
Date
2022-01-01   12.0   67.0   NaN
2022-01-02    NaN    NaN  20.0
2022-01-04  194.0  174.0   8.0
2022-01-05   26.0   37.0   NaN
2022-01-07    NaN    1.0  15.0
2022-01-08    NaN    NaN  98.0
2022-01-09  128.0   10.0   NaN
2022-01-10   53.0    NaN   NaN

2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

In [27]:
# Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'
df = pd.DataFrame({'Year': np.random.choice([2020, 2021, 2022], size=12), 'Quarter': np.random.choice(['Q1', 'Q2', 'Q3', 'Q4'], size=12), 'Revenue': np.random.randint(1, 1000, size=12)})
print("Original DataFrame:")
print(df)

# Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'
pivot_table = df.pivot_table(values='Revenue', index='Year', columns='Quarter', aggfunc='mean')
print("Pivot Table:")
print(pivot_table)

Original DataFrame:
    Year Quarter  Revenue
0   2021      Q1      709
1   2020      Q1      207
2   2020      Q3      382
3   2020      Q1      784
4   2020      Q1      700
5   2021      Q4      690
6   2022      Q1      605
7   2021      Q1      204
8   2021      Q2      709
9   2020      Q1      955
10  2022      Q2      281
11  2022      Q4      599
Pivot Table:
Quarter     Q1     Q2     Q3     Q4
Year
2020     661.5    NaN  382.0    NaN
2021     456.5  709.0    NaN  690.0
2022     605.0  281.0    NaN  599.0

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.

In [32]:

def double(val):
    return val+val

df=pd.DataFrame(np.random.randint(1,10,size=(5,3)))
dfd=df.apply(double)
dfd

    0   1   2
0   6   4  16
1   2  14   2
2   8  16  16
3  18  14   6
4  18  10  10

2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

In [33]:
df=pd.DataFrame(np.random.randint(1,10,size=(6,3)))
df

df['Sum']=df.apply(lambda row:row.sum(),axis=1)
df

   0  1  2  Sum
0  9  7  9   25
1  2  7  4   13
2  7  5  3   15
3  3  7  2   12
4  9  1  5   15
5  3  7  7   17

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.

In [25]:
ser=pd.Series(['App','ipj','jfe','CJHVSCJSH','JHCvfhj'])
print(ser)
print(ser.str.upper())

0          App
1          ipj
2          jfe
3    CJHVSCJSH
4      JHCvfhj
dtype: object
0          APP
1          IPJ
2          JFE
3    CJHVSCJSH
4      JHCVFHJ
dtype: object

2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

In [28]:
ser=pd.Series(['App','ipj','jfe','CJHVSCJSH','JHCvfhj'])
print(ser)
print(ser.str[:3])

0          App
1          ipj
2          jfe
3    CJHVSCJSH
4      JHCvfhj
dtype: object
0    App
1    ipj
2    jfe
3    CJH
4    JHC
dtype: object