# gaussian Naive bayes on the tips dataset

In [37]:
# Import the necessary libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.model_selection import train_test_split,GridSearchCV,StratifiedKFold,KFold
from sklearn.compose import ColumnTransformer

from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [11]:
# Load the tips dataset


dataset=sns.load_dataset('tips')

In [19]:
dataset

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [21]:
dataset.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [20]:
dataset['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [23]:
X=dataset[['total_bill', 'tip', 'sex', 'smoker', 'time', 'size']]

In [25]:
y=dataset['day']

In [26]:
y

0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ...
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [24]:
X

     total_bill   tip     sex smoker    time  size
0         16.99  1.01  Female     No  Dinner     2
1         10.34  1.66    Male     No  Dinner     3
2         21.01  3.50    Male     No  Dinner     3
3         23.68  3.31    Male     No  Dinner     2
4         24.59  3.61  Female     No  Dinner     4
..          ...   ...     ...    ...     ...   ...
239       29.03  5.92    Male     No  Dinner     3
240       27.18  2.00  Female    Yes  Dinner     2
241       22.67  2.00    Male    Yes  Dinner     2
242       17.82  1.75    Male     No  Dinner     2
243       18.78  3.00  Female     No  Dinner     2

[244 rows x 6 columns]

In [27]:
# we have 3 binary class feature and 1 multi class feature. for the binary class we implement LabelEncoding and for the multiclass we implement OHE

#Just To make Sure the Data does not leak (Dataleakage) We first perfrom train test split then implement this encoding

X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.30)

In [29]:
y_train

234    Sat
227    Sat
180    Sun
5      Sun
56     Sat
      ...
106    Sat
14     Sun
92     Fri
179    Sun
102    Sat
Name: day, Length: 170, dtype: category
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [30]:
lb1=LabelEncoder()
lb2=LabelEncoder()
lb4=LabelEncoder()

In [31]:


X_train['sex']=lb1.fit_transform(X_train['sex'])
X_train['smoker']=lb2.fit_transform(X_train['smoker'])
X_train['time']=lb4.fit_transform(X_train['time'])

# Not A best preactise always use label encoder only for output features, for input use only OHE

In [32]:
X_test['sex']=lb1.fit_transform(X_test['sex'])
X_test['smoker']=lb2.fit_transform(X_test['smoker'])
X_test['time']=lb4.fit_transform(X_test['time'])

In [33]:
X_train

     total_bill   tip  sex  smoker  time  size
234       15.53  3.00    1       1     0     2
227       20.45  3.00    1       0     0     4
180       34.65  3.68    1       1     0     4
5         25.29  4.71    1       0     0     4
56        38.01  3.00    1       1     0     4
..          ...   ...  ...     ...   ...   ...
106       20.49  4.06    1       1     0     2
14        14.83  3.02    0       0     0     2
92         5.75  1.00    0       1     0     2
179       34.63  3.55    1       1     0     2
102       44.30  2.50    0       1     0     3

[170 rows x 6 columns]

In [34]:
gnb=GaussianNB()

In [35]:
gnb.fit(X_train,y_train)

GaussianNB()

In [36]:
y_predicted=gnb.predict(X_test)

In [39]:
print(f'accuracy_score: {accuracy_score(y_pred=y_predicted,y_true=y_test)}')
print(f'classification_report:\n {classification_report(y_pred=y_predicted,y_true=y_test)}\n')
print(f'confusion Matrix:\n {confusion_matrix(y_pred=y_predicted,y_true=y_test)}')

accuracy_score: 0.7027027027027027
classification_report:
               precision    recall  f1-score   support

         Fri       0.00      0.00      0.00         4
         Sat       0.63      0.61      0.62        28
         Sun       0.61      0.71      0.65        24
        Thur       0.95      1.00      0.97        18

    accuracy                           0.70        74
   macro avg       0.55      0.58      0.56        74
weighted avg       0.67      0.70      0.68        74


confusion Matrix:
 [[ 0  3  0  1]
 [ 0 17 11  0]
 [ 0  7 17  0]
 [ 0  0  0 18]]

d:\Udemy\DataScience\ML-DL-NLP\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Udemy\DataScience\ML-DL-NLP\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
d:\Udemy\DataScience\ML-DL-NLP\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])