In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [ ]:
df=pd.DataFrame(
    {
        'color':['red','blue','green','blue','green','red','blue','green','red']
    }
)

In [ ]:
df.head()

In [ ]:
ohe=OneHotEncoder()

In [ ]:
encoded=ohe.fit_transform(df[['color']]).toarray()
df=pd.DataFrame(data=encoded,columns=ohe.get_feature_names_out())

In [ ]:
df

# Encode all the categorical data in seaborn tips dataset

In [45]:
import seaborn as sns

dataset=sns.load_dataset('tips')

In [46]:
dataset

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [47]:
dataset.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [48]:
dataset.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [49]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
encoder=OneHotEncoder()
sex_encoded=encoder.fit_transform(dataset[['sex']]).toarray()
sex_df=pd.DataFrame(sex_encoded,columns=encoder.get_feature_names_out())
dataset=dataset.join(sex_df,how='inner')

In [50]:
dataset

     total_bill   tip     sex smoker   day    time  size  sex_Female  sex_Male
0         16.99  1.01  Female     No   Sun  Dinner     2         1.0       0.0
1         10.34  1.66    Male     No   Sun  Dinner     3         0.0       1.0
2         21.01  3.50    Male     No   Sun  Dinner     3         0.0       1.0
3         23.68  3.31    Male     No   Sun  Dinner     2         0.0       1.0
4         24.59  3.61  Female     No   Sun  Dinner     4         1.0       0.0
..          ...   ...     ...    ...   ...     ...   ...         ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         0.0       1.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         1.0       0.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0.0       1.0
242       17.82  1.75    Male     No   Sat  Dinner     2         0.0       1.0
243       18.78  3.00  Female     No  Thur  Dinner     2         1.0       0.0

[244 rows x 9 columns]

In [51]:
smoker_encoded=encoder.fit_transform(dataset[['smoker']]).toarray()
smoker_df=pd.DataFrame(smoker_encoded,columns=encoder.get_feature_names_out())
dataset=dataset.join(smoker_df,how='inner')

In [52]:
dataset

     total_bill   tip     sex  ... sex_Male smoker_No smoker_Yes
0         16.99  1.01  Female  ...      0.0       1.0        0.0
1         10.34  1.66    Male  ...      1.0       1.0        0.0
2         21.01  3.50    Male  ...      1.0       1.0        0.0
3         23.68  3.31    Male  ...      1.0       1.0        0.0
4         24.59  3.61  Female  ...      0.0       1.0        0.0
..          ...   ...     ...  ...      ...       ...        ...
239       29.03  5.92    Male  ...      1.0       1.0        0.0
240       27.18  2.00  Female  ...      0.0       0.0        1.0
241       22.67  2.00    Male  ...      1.0       0.0        1.0
242       17.82  1.75    Male  ...      1.0       1.0        0.0
243       18.78  3.00  Female  ...      0.0       1.0        0.0

[244 rows x 11 columns]

In [53]:
day_encoded=encoder.fit_transform(dataset[['day']]).toarray()
day_df=pd.DataFrame(day_encoded,columns=encoder.get_feature_names_out())
dataset=dataset.join(day_df,how='inner')

In [54]:
dataset

     total_bill   tip     sex smoker  ... day_Fri day_Sat  day_Sun  day_Thur
0         16.99  1.01  Female     No  ...     0.0     0.0      1.0       0.0
1         10.34  1.66    Male     No  ...     0.0     0.0      1.0       0.0
2         21.01  3.50    Male     No  ...     0.0     0.0      1.0       0.0
3         23.68  3.31    Male     No  ...     0.0     0.0      1.0       0.0
4         24.59  3.61  Female     No  ...     0.0     0.0      1.0       0.0
..          ...   ...     ...    ...  ...     ...     ...      ...       ...
239       29.03  5.92    Male     No  ...     0.0     1.0      0.0       0.0
240       27.18  2.00  Female    Yes  ...     0.0     1.0      0.0       0.0
241       22.67  2.00    Male    Yes  ...     0.0     1.0      0.0       0.0
242       17.82  1.75    Male     No  ...     0.0     1.0      0.0       0.0
243       18.78  3.00  Female     No  ...     0.0     0.0      0.0       1.0

[244 rows x 15 columns]

In [55]:
time_encoded=encoder.fit_transform(dataset[['time']]).toarray()
time_df=pd.DataFrame(time_encoded,columns=encoder.get_feature_names_out())
dataset=dataset.join(time_df,how='inner')

In [56]:
dataset

     total_bill   tip     sex  ... day_Thur time_Dinner time_Lunch
0         16.99  1.01  Female  ...      0.0         1.0        0.0
1         10.34  1.66    Male  ...      0.0         1.0        0.0
2         21.01  3.50    Male  ...      0.0         1.0        0.0
3         23.68  3.31    Male  ...      0.0         1.0        0.0
4         24.59  3.61  Female  ...      0.0         1.0        0.0
..          ...   ...     ...  ...      ...         ...        ...
239       29.03  5.92    Male  ...      0.0         1.0        0.0
240       27.18  2.00  Female  ...      0.0         1.0        0.0
241       22.67  2.00    Male  ...      0.0         1.0        0.0
242       17.82  1.75    Male  ...      0.0         1.0        0.0
243       18.78  3.00  Female  ...      1.0         1.0        0.0

[244 rows x 17 columns]

# Label Encoding

In [57]:
df=pd.DataFrame(
    {
        'color':['red','blue','green','blue','green','red','blue','green','red']
    }
)
df.head()

   color
0    red
1   blue
2  green
3   blue
4  green

In [62]:
from sklearn.preprocessing import LabelEncoder

lbl_encoder=LabelEncoder()
lbl_encoded=lbl_encoder.fit_transform(df['color'])

In [63]:
lbl_encoded

array([2, 0, 1, 0, 1, 2, 0, 1, 2])

In [64]:
lbl_encoder.transform(['red'])

array([2])