In [31]:
# Import All the necessary Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [64]:
# Create Dataset
np.random.seed(23)

mu_vec1 = np.array([0, 0, 0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample, columns=['feature1','feature2','feature3'])
df['target'] = 1

mu_vec2 = np.array([1, 1, 1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample, columns=['feature1','feature2','feature3'])
df1['target'] = 0

# ✅ Correct way to combine DataFrames
df = pd.concat([df, df1], ignore_index=True)

# Shuffle dataset
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [33]:
df

    feature1  feature2  feature3  target
0  -0.992574 -0.161346  1.192404       1
1  -0.420844 -0.551989 -0.121098       1
2  -0.045438  1.040886 -0.094035       1
3   0.898907  0.435960  0.820964       0
4   0.322272  0.060343 -1.043450       1
5  -2.506230  0.146960  0.606195       1
6  -1.027861  1.131416  2.603234       0
7   2.011059  1.920996  2.933090       0
8   0.384865  1.323546 -0.103193       0
9  -1.838068 -0.938769 -0.201841       1
10  0.290746  0.866975  0.982643       0
11  1.267248  0.173634 -1.223255       1
12 -0.022539  0.013422  0.935945       1
13  2.224431  0.230401  1.192120       0
14  0.177061 -0.598109  1.226512       0
15  0.241106 -0.952510 -0.136267       1
16  0.190141  0.512137  0.131538       1
17  0.748855  2.593111  1.170818       0
18  0.666988  0.025813 -0.777619       1
19  2.823378 -0.332863  2.637391       0
20 -1.009942  0.441736  1.128877       1
21  1.968435 -0.547788 -0.679418       1
22  0.948634  0.701672 -1.051082       1
23  1.425140  1.441152  0.182561       0
24  0.731858  0.517441  2.244610       0
25 -0.367548 -1.137460 -1.322148       1
26  1.437892  1.099723  1.065406       0
27 -1.389866  0.666726  1.343517       0
28  1.772258 -0.347459  0.670140       1
29  1.233898  0.052778 -0.261576       0
30  1.010229  1.437830  2.327788       0
31 -0.723253  1.461259 -0.085367       0
32  1.415320  0.457711  0.728876       1
33  1.676860  4.187503 -0.080565       0
34 -0.331617 -1.632386  0.619114       1
35  1.250737  0.186384  1.703624       0
36  1.045371  0.538162  0.812119       1
37  0.420623  0.411620 -0.071324       1
38  0.204637 -0.011535  3.150780       0
39 -0.764314  1.566504  1.548788       0

# PCA Without any Libraries
1. **Standardize data** (important!)
2. Compute **covariance matrix** (\Sigma)
3. Compute **eigenvectors & eigenvalues** of (\Sigma)

   * Eigenvectors → directions (PCs)
   * Eigenvalues → variance captured
4. Sort by eigenvalues (descending)
5. Project data onto top (k) eigenvectors

In [34]:
df

    feature1  feature2  feature3  target
0  -0.992574 -0.161346  1.192404       1
1  -0.420844 -0.551989 -0.121098       1
2  -0.045438  1.040886 -0.094035       1
3   0.898907  0.435960  0.820964       0
4   0.322272  0.060343 -1.043450       1
5  -2.506230  0.146960  0.606195       1
6  -1.027861  1.131416  2.603234       0
7   2.011059  1.920996  2.933090       0
8   0.384865  1.323546 -0.103193       0
9  -1.838068 -0.938769 -0.201841       1
10  0.290746  0.866975  0.982643       0
11  1.267248  0.173634 -1.223255       1
12 -0.022539  0.013422  0.935945       1
13  2.224431  0.230401  1.192120       0
14  0.177061 -0.598109  1.226512       0
15  0.241106 -0.952510 -0.136267       1
16  0.190141  0.512137  0.131538       1
17  0.748855  2.593111  1.170818       0
18  0.666988  0.025813 -0.777619       1
19  2.823378 -0.332863  2.637391       0
20 -1.009942  0.441736  1.128877       1
21  1.968435 -0.547788 -0.679418       1
22  0.948634  0.701672 -1.051082       1
23  1.425140  1.441152  0.182561       0
24  0.731858  0.517441  2.244610       0
25 -0.367548 -1.137460 -1.322148       1
26  1.437892  1.099723  1.065406       0
27 -1.389866  0.666726  1.343517       0
28  1.772258 -0.347459  0.670140       1
29  1.233898  0.052778 -0.261576       0
30  1.010229  1.437830  2.327788       0
31 -0.723253  1.461259 -0.085367       0
32  1.415320  0.457711  0.728876       1
33  1.676860  4.187503 -0.080565       0
34 -0.331617 -1.632386  0.619114       1
35  1.250737  0.186384  1.703624       0
36  1.045371  0.538162  0.812119       1
37  0.420623  0.411620 -0.071324       1
38  0.204637 -0.011535  3.150780       0
39 -0.764314  1.566504  1.548788       0

In [35]:

fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
              color=df['target'].astype('str'))
fig.show()

In [36]:
X=df.iloc[:,0:3]
y=df.iloc[:,-1]

In [37]:
X

    feature1  feature2  feature3
0  -0.992574 -0.161346  1.192404
1  -0.420844 -0.551989 -0.121098
2  -0.045438  1.040886 -0.094035
3   0.898907  0.435960  0.820964
4   0.322272  0.060343 -1.043450
5  -2.506230  0.146960  0.606195
6  -1.027861  1.131416  2.603234
7   2.011059  1.920996  2.933090
8   0.384865  1.323546 -0.103193
9  -1.838068 -0.938769 -0.201841
10  0.290746  0.866975  0.982643
11  1.267248  0.173634 -1.223255
12 -0.022539  0.013422  0.935945
13  2.224431  0.230401  1.192120
14  0.177061 -0.598109  1.226512
15  0.241106 -0.952510 -0.136267
16  0.190141  0.512137  0.131538
17  0.748855  2.593111  1.170818
18  0.666988  0.025813 -0.777619
19  2.823378 -0.332863  2.637391
20 -1.009942  0.441736  1.128877
21  1.968435 -0.547788 -0.679418
22  0.948634  0.701672 -1.051082
23  1.425140  1.441152  0.182561
24  0.731858  0.517441  2.244610
25 -0.367548 -1.137460 -1.322148
26  1.437892  1.099723  1.065406
27 -1.389866  0.666726  1.343517
28  1.772258 -0.347459  0.670140
29  1.233898  0.052778 -0.261576
30  1.010229  1.437830  2.327788
31 -0.723253  1.461259 -0.085367
32  1.415320  0.457711  0.728876
33  1.676860  4.187503 -0.080565
34 -0.331617 -1.632386  0.619114
35  1.250737  0.186384  1.703624
36  1.045371  0.538162  0.812119
37  0.420623  0.411620 -0.071324
38  0.204637 -0.011535  3.150780
39 -0.764314  1.566504  1.548788

In [38]:
y

0     1
1     1
2     1
3     0
4     1
5     1
6     0
7     0
8     0
9     1
10    0
11    1
12    1
13    0
14    0
15    1
16    1
17    0
18    1
19    0
20    1
21    1
22    1
23    0
24    0
25    1
26    0
27    0
28    1
29    0
30    0
31    0
32    1
33    0
34    1
35    0
36    1
37    1
38    0
39    0
Name: target, dtype: int64

In [42]:
# Step 1: Standardize the Values
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
X=scaler.fit_transform(X=X)

In [ ]:
#Convert np array to Dataframe
X_Scaled=pd.DataFrame(X,columns=['feature1','feature2','feature3'])

In [48]:
# Construct Covarinece Matrix
covarienceMatrix=X_Scaled.cov()

In [51]:
# Extract eigen values and eigen vectors

eigenValues,eigenVectors=np.linalg.eig(covarienceMatrix)

In [52]:
eigenValues

array([1.3536065 , 0.94557084, 0.77774573])

In [53]:
eigenVectors

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

In [54]:
# As We are converting 3D to 2D (Converting 3 features to 2 features), we select top 2 highest eigen values and eigen vectors these are principal components
pc=eigenVectors[:2]

In [55]:
pc

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442]])

In [56]:
# For the final step. Calculate the dot product of the row and transposed principal component

transformedDF=np.dot(df.iloc[:,:3],pc.T)

In [58]:
# New Trasformed Dataset
transformedDF

array([[ 1.21680223, -0.24688808],
       [ 0.55171013,  0.37332843],
       [-0.74247404,  0.08976243],
       [-0.39416002, -1.21388016],
       [-0.71439133,  0.57532729],
       [ 1.53816046,  1.18529762],
       [ 1.01367616, -1.30204154],
       [-1.01353278, -3.55309026],
       [-1.17474465, -0.18862998],
       [ 1.54492986,  1.36816562],
       [-0.2881699 , -0.94143936],
       [-1.38805908,  0.08982903],
       [ 0.45033984, -0.69163208],
       [-0.78825331, -2.36143911],
       [ 0.90591152, -1.03538483],
       [ 0.46563998, -0.04528325],
       [-0.39478276, -0.22942573],
       [-1.64231177, -1.40225175],
       [-0.74905688,  0.14893013],
       [-0.02920981, -3.83906426],
       [ 0.77746677, -0.19393259],
       [-1.00540131, -0.77296485],
       [-1.50034546,  0.16335769],
       [-1.68014894, -1.08801501],
       [ 0.32001533, -2.17944754],
       [ 0.35483591,  1.25088347],
       [-1.0280753 , -1.75897858],
       [ 0.92872063, -0.10902073],
       [-0.39339469, -1.66477169],
       [-0.82645052, -0.6127088 ],
       [-0.42860223, -2.43458305],
       [-0.66473501,  0.523479  ],
       [-0.73149979, -1.48342868],
       [-3.84653413, -1.08365136],
       [ 1.60695799, -0.23235992],
       [ 0.01143243, -2.10813744],
       [-0.54818878, -1.30437862],
       [-0.54622962, -0.22649469],
       [ 1.40424576, -2.51176074],
       [ 0.06573029, -0.68385171]])

In [60]:
# Now Convert this to dataset
new_df = pd.DataFrame(transformedDF,columns=['PC1','PC2'])
new_df['target'] = df['target'].values
new_df.head()

        PC1       PC2  target
0  1.216802 -0.246888       1
1  0.551710  0.373328       1
2 -0.742474  0.089762       1
3 -0.394160 -1.213880       0
4 -0.714391  0.575327       1

In [62]:
# New 2D Diagram
new_df['target'] = new_df['target'].astype('str')
fig = px.scatter(x=new_df['PC1'],
                 y=new_df['PC2'],
                 color=new_df['target'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )
fig.show()

# PCA Using sklearn Library

In [65]:
df

    feature1  feature2  feature3  target
0  -0.992574 -0.161346  1.192404       1
1  -0.420844 -0.551989 -0.121098       1
2  -0.045438  1.040886 -0.094035       1
3   0.898907  0.435960  0.820964       0
4   0.322272  0.060343 -1.043450       1
5  -2.506230  0.146960  0.606195       1
6  -1.027861  1.131416  2.603234       0
7   2.011059  1.920996  2.933090       0
8   0.384865  1.323546 -0.103193       0
9  -1.838068 -0.938769 -0.201841       1
10  0.290746  0.866975  0.982643       0
11  1.267248  0.173634 -1.223255       1
12 -0.022539  0.013422  0.935945       1
13  2.224431  0.230401  1.192120       0
14  0.177061 -0.598109  1.226512       0
15  0.241106 -0.952510 -0.136267       1
16  0.190141  0.512137  0.131538       1
17  0.748855  2.593111  1.170818       0
18  0.666988  0.025813 -0.777619       1
19  2.823378 -0.332863  2.637391       0
20 -1.009942  0.441736  1.128877       1
21  1.968435 -0.547788 -0.679418       1
22  0.948634  0.701672 -1.051082       1
23  1.425140  1.441152  0.182561       0
24  0.731858  0.517441  2.244610       0
25 -0.367548 -1.137460 -1.322148       1
26  1.437892  1.099723  1.065406       0
27 -1.389866  0.666726  1.343517       0
28  1.772258 -0.347459  0.670140       1
29  1.233898  0.052778 -0.261576       0
30  1.010229  1.437830  2.327788       0
31 -0.723253  1.461259 -0.085367       0
32  1.415320  0.457711  0.728876       1
33  1.676860  4.187503 -0.080565       0
34 -0.331617 -1.632386  0.619114       1
35  1.250737  0.186384  1.703624       0
36  1.045371  0.538162  0.812119       1
37  0.420623  0.411620 -0.071324       1
38  0.204637 -0.011535  3.150780       0
39 -0.764314  1.566504  1.548788       0

In [80]:
from sklearn.decomposition import PCA

pc=PCA(n_components=2,copy=False)
newDF=pc.fit_transform(df.iloc[:,:3])
dataset=pd.DataFrame(newDF,columns=['pc1','pc2'],index=df.index)
dataset=pd.concat([dataset,df.iloc[:,-1]],axis=1)

In [81]:
dataset

         pc1       pc2  target
0  -0.901546  1.361674       1
1  -1.525553  0.015335       1
2  -0.420981 -0.213623       1
3   0.359291 -0.211671       0
4  -1.276698 -1.160256       1
5  -1.998517  1.988996       1
6   0.593145  2.413288       0
7   3.064530  0.552818       0
8  -0.011212 -0.516138       0
9  -2.645724  0.935578       1
10  0.314750  0.329162       0
11 -0.743377 -1.943464       1
12 -0.364216  0.506253       1
13  1.272219 -0.863150       0
14 -0.404028  0.573295       0
15 -1.346755 -0.456818       1
16 -0.431857 -0.217788       1
17  1.635164  0.160139       0
18 -0.930856 -1.207392       1
19  2.171864 -0.239165       0
20 -0.623433  1.332200       1
21 -0.389620 -2.041777       1
22 -0.552824 -1.594843       1
23  0.852622 -1.029406       0
24  1.127161  0.931716       0
25 -2.505764 -0.892313       1
26  1.188188 -0.403731       0
27 -0.609240  1.751733       0
28  0.381665 -0.930821       1
29 -0.271138 -1.227406       0
30  1.842068  0.805598       0
31 -0.602511  0.264967       0
32  0.632641 -0.635516       1
33  2.336089 -1.373801       0
34 -1.624982  0.479841       1
35  0.951178  0.179755       0
36  0.498677 -0.318730       1
37 -0.463190 -0.524456       1
38  1.045617  1.946746       0
39  0.377151  1.473170       0